### ISSUE TITLE
Torrents don't load to put.io correctly

### ISSUE THREAD

**Issue by cjunge** [yuhui/Put.io-add-on-for-Firefox#1]
I'm running put.io addon version 1.0.5-20120304 on Firefox 11 on Linux and when I send a link for a torrent file to Put.io it loads with no title, and doesn't seem to download. Just shows "downloading" and no other information.

If I download the torrent file & use the "Upload from computer" option it loads correctly.

Cheers

**Comment by yuhui** [comment]
Sorry for the late reply. Do you have any sample torrent URLs that don't download?

**Comment by cjunge** [comment]
http://www.demonoid.me/files/download/2957951/ is one that doesn't work right.
